name: Code Quality Checks
on:
  push:
    branches:
      - dev
      - main
      - release/**
  pull_request:
    branches:
      - dev
      - main
      - release/**
  workflow_call:
  workflow_dispatch: {}
defaults:
  run:
    working-directory: .
jobs:
  code-quality:
    timeout-minutes: 10
    strategy:
      matrix:
        runner_image:
          - "ubuntu-20.04"
          - "macos-11"
        python_version:
          - "3.7"
          - "3.8"
          - "3.9"
        pip_deps:
          - "[all]"
    runs-on: ${{ matrix.runner_image }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}
      - name: Setup
        run: |
          set -ex
          python -m pip install --upgrade pip wheel
          python -m pip install -e .${{ matrix.pip_deps }}
      - name: Run checks
        run: |
          pre-commit run --all-files
